version: 0.2
phases:
  install:
    commands:
      - echo "Updating the build environment"
      # Purely informational
      - aws --version
      # Upgrade pip
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Installing PIP packages
      - for dir in $(find lambdas -maxdepth 1 -type d | sed -e 's/\.\///g'); do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install --no-compile -t "$dir"/package/ -r "$dir"/requirements.txt); fi; done
      - echo Removing compiled files
      - rm -f $(find lambdas/ -name *.pyc -type f)
  build:
    commands:
      - echo Zip lambdas
      - cd lambdas ; for dir in $(ls); do echo "$dir"; cd "$dir"; zip -r "$dir".zip ./ ; cd .. ; done
      - cd ..
  post_build:
    commands:
      - for zipfile in $(ls lambdas/*/*.zip); do aws s3 cp "$zipfile" s3://"${LambdaBucket}"/ ; done