version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing PIP packages
      - for dir in $(find lambdas -maxdepth 1 -type d | sed -e 's/\.\///g'); do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install --no-compile -t "$dir"/package/ -r "$dir"/requirements.txt); fi; done
      - echo Removing compiled files
      - rm -vf $(find lambdas/ -name *.pyc -type f)
      - pwd
  build:
    commands:
      - echo Zip lambdas
      - cd lambdas ; for dir in $(find . -maxdepth 1 -type d \( ! -iname "." \) | sed -e 's/\.\///g'); do echo "$dir"; cd "$dir"; zip -r "$dir"-"$LambdaVersion".zip ./ ; cd .. ; done
      - cd ..
      - pwd
  post_build:
    commands:
      - for zipfile in $(ls lambdas/*/*.zip); do aws s3 cp "$zipfile" s3://"${LambdaBucket}"/"$zipfile" ; done