version: 0.2
phases:
  install:
    commands:
      echo "Updating the build environment"
      # Purely informational
      - aws --version
      # Upgrade pip
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Installing PIP packages
      - for dir in lambdas/*; do echo "$dir"; if [ -f "$dir"/requirements.txt ]; then (pip install --no-compile -t "$dir"/package/ -r "$dir"/requirements.txt); fi; done
      - echo Removing compiled files
      - rm -f $(find lambdas/ -name *.pyc -type f)
  build:
    commands:
      - echo Zip lambdas
      - cd lambdas ; for dir in $(find . -type d -depth 1 | sed -e 's/\.\///g'); do cd "$dir"; zip -r "$dir".zip ./ ; cd .. ; done
  post_build:
    commands:
      - for zipfile in lambdas/*/*.zip; do aws s3 cp "$zipfile" s3://"${LambdaBucket}"/